cmdb/urls.py
from django.conf.urls import include, url, patterns
#from assets import rest_urls,urls as asset_urls
from hosts import hosts_urls,assets_urls,perm_urls,api_urls,salog_urls,cdn_urls,sdk_urls
from manager import manager_urls,help_urls
from inc import inc_urls
from multitask import multi_urls
from multitask import web_urls
from scripting import script_urls
from scripting import cron_urls

import views
from django.conf.urls import handler404, handler500

handler404 = "cmdb.views.page_not_found"
handler500 = "cmdb.views.page_error"

urlpatterns = patterns('',
       (r'^$', views.index),
       (r'^skin_config/$', views.skin_config),
       (r'^login/$', views.account_login),
       (r'^checkcode/$', views.CheckCode),
       (r'^accounts/login/$', views.account_login),
       (r'^logout/$', views.account_logout),
       (r'^monitor/$', views.monitor),
       (r'^warning/$', views.monitor),
       #(r'^monitor/mail$', views.mail),
       (r'^asset/', include(assets_urls)),
       (r'^manager/', include(manager_urls)),
       (r'^inc/', include(inc_urls)),
       (r'^hosts/', include(hosts_urls)),
       (r'^perm/', include(perm_urls)),
       (r'^multitask/', include(multi_urls)),
       (r'^web/', include(web_urls)),
       (r'^scripting/', include(script_urls)),
       (r'^crontab/', include(cron_urls)),
       (r'^api/', include(api_urls)),
       (r'^help/', include(help_urls)),
       (r'^salog/', include(salog_urls)),
       (r'^cdn/', include(cdn_urls)),
       (r'^sdk/', include(sdk_urls)),
    url(r'^personal/$', views.personal, name="personal"),
    url(r'^highchart_api/$', views.highchart_api, name="highchart_api"),
    url(r'^highchart_pie/$', views.highchart_pie, name="highchart_pie"),
)



hosts/models.py
#_*_coding:utf-8_*_
from django.db import models
from manager.myauth import *
# Create your models here.

ASSET_STATUS = (
    (1, u"已使用"),
    (2, u"未使用"),
    (3, u"已报废"),
    (4, u"已下架")
    )

ASSET_TYPE = (
    (1, u"物理机"),
    (2, u"虚拟机"),
    (3, u"交换机"),
    (4, u"路由器"),
    (5, u"防火墙"),
    (6, u"Docker"),
    (7, u"其他")
    )

RECORD_TYPE = (
    (1, u'CNAME'),
    (2, u'A')
)

COST_TYPE = (
    (1, u'云服务器'),
    (2, u'云数据库'),
    (3, u'内存存储'),
    (4, u'CDN'),
    (5, u'云硬盘')
)

REPOS_TYPE = (
    (1,u'svn'),
    (2,u'git'),
)
class ReposManager(models.Model):
    repos_name = models.CharField(u'名称或用途',max_length=64,unique=True)
    project = models.ForeignKey(Project, default=None, blank=True, null=True, on_delete=models.SET_NULL,
                                verbose_name=u"项目")
    repos_type = models.IntegerField(choices=REPOS_TYPE, blank=True, null=True, verbose_name=u"仓库类型")
    repos_addr = models.CharField(u'地址',max_length=128,blank=True,null=True)
    repos_user = models.CharField(u'认证用户',max_length=32,blank=True,null=True)
    repos_pass = models.CharField(u'认证密码',max_length=32,blank=True,null=True)

    class Meta:
        verbose_name = u'发布仓库管理'
        verbose_name_plural = u'发布仓库管理'
    def __unicode__(self):
        return self.repos_name

class server_use(models.Model):
    use_name = models.CharField(max_length=128,unique=True)
    class Meta:
        verbose_name = u'服务器用途'
        verbose_name_plural = u'服务器用途'
    def __unicode__(self):
        return self.use_name

class area_type(models.Model):
    area_name = models.CharField(max_length=64,unique=True)
    mini_name = models.CharField(max_length=32,unique=True)
    class Meta:
        verbose_name = u'地区管理'
        verbose_name_plural = u'地区管理'
    def __unicode__(self):
        return self.area_name

class idc_list(models.Model):
    idc_name = models.CharField(max_length=64,unique=True, verbose_name=u'机房名称')
    mini_name = models.CharField(max_length=32,unique=True)
    net_line = models.CharField(max_length=32,blank=True, null=True,verbose_name=u'机房线路')
    bandwidth = models.CharField(max_length=32, blank=True, null=True, default='', verbose_name=u'机房带宽')
    linkman = models.CharField(max_length=16, blank=True, null=True, default='', verbose_name=u'联系人')
    phone = models.CharField(max_length=32, blank=True, null=True, default='', verbose_name=u'联系电话')
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")
    class Meta:
        verbose_name = u'IDC管理'
        verbose_name_plural = u'IDC管理'
    def __unicode__(self):
        return self.idc_name

class platform_type(models.Model):
    plat_name = models.CharField(max_length=64,unique=True)
    mini_name = models.CharField(max_length=32,unique=True)
    class Meta:
        verbose_name = u'平台类型管理'
        verbose_name_plural = u'平台类型管理'

    def __unicode__(self):
        return self.plat_name

class publisher(models.Model):
    name = models.CharField(max_length=128,unique=True)
    mini_name = models.CharField(max_length=32,unique=True)
    access_time = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name = u'发行商管理'
        verbose_name_plural = u'发行商管理'

    def __unicode__(self):
        return self.name

class CostManger(models.Model):
    project = models.ForeignKey(Project,default=None,blank=True,null=True,on_delete=models.SET_NULL,verbose_name=u"项目")
    cost_type = models.IntegerField(choices=COST_TYPE, blank=True, null=True,verbose_name=u"云服务类型")
    idc = models.ForeignKey(idc_list,blank=True,null=True,on_delete=models.SET_NULL)
    cpu = models.IntegerField(u'CPU核数',blank=True,null=True)
    mem = models.IntegerField(u'内存(GB)',blank=True,null=True)
    disk = models.IntegerField(u'硬盘(GB)',blank=True,null=True)
    bandwidth = models.IntegerField(u'带宽(MB)',blank=True,null=True)
    network_bill = models.BooleanField(u'流量计费',default=False)
    price = models.CharField(u'月单价',max_length=100,blank=True,null=True)
    start_date = models.DateTimeField(u'开始时间',auto_now_add=True)
    status = models.IntegerField(choices=ASSET_STATUS,default=1)
    total = models.IntegerField(u'数量',default=1)

    class Meta:
        verbose_name = u'费用管理'
        verbose_name_plural = u'费用管理'

    def __unicode__(self):
        return self.project.name

class host(models.Model):
    hostname = models.CharField(max_length=255,unique=True,blank=True,null=True)
    p_ip = models.GenericIPAddressField(unique=True)
    s_ip = models.GenericIPAddressField(blank=True,null=True)
    db_ip = models.CharField(max_length=255,blank=True,null=True)
    port = models.IntegerField(default=22)
    os_type = models.CharField(max_length=32)
    platform = models.ForeignKey(platform_type,blank=True,null=True,on_delete=models.SET_NULL)
    project = models.ForeignKey(Project,default=None,blank=True,null=True,on_delete=models.SET_NULL)
    use = models.ManyToManyField(server_use)
    area = models.ForeignKey(area_type,blank=True,null=True,on_delete=models.SET_NULL)
    idc = models.ForeignKey(idc_list,blank=True,null=True,on_delete=models.SET_NULL)
    login_pass = models.CharField(max_length=255,null=True,blank=True)
    game_count = models.IntegerField(default=0,null=True,blank=True)
    commit = models.CharField(max_length=255,null=True,blank=True)
    host_init = models.BooleanField(default=False)
    db_init = models.BooleanField(default=False)
    asset_status = models.IntegerField(default=0,null=True,blank=True)
    online_date = models.DateTimeField(auto_now_add=True)
    recover = models.IntegerField(default=0,null=True,blank=True)
    recover_date = models.DateTimeField(blank=True,null=True)

    class Meta:
        verbose_name = u'服务器列表'
        verbose_name_plural = u'服务器列表'
    def __unicode__(self):
        return self.p_ip

class DomainInfo(models.Model):
    project = models.ForeignKey(Project,default=None,blank=True,null=True,on_delete=models.SET_NULL,verbose_name="项目")
    domain_name = models.CharField(u'域名',max_length=128)
    record_type = models.IntegerField(choices=RECORD_TYPE, blank=True, null=True, verbose_name=u"记录类型")
    order_key = models.CharField(u'记录值',max_length=128,blank=True,null=True)
    remark = models.CharField(u'备注用途',max_length=255,blank=True,null=True)
    contacts = models.CharField(u'联系人',max_length=64,blank=True,null=True)
    status = models.BooleanField(default=True)
    online_date = models.DateTimeField(auto_now_add=True)
    operator = models.ForeignKey(UserProfile, max_length=84, verbose_name="管理员")

    class Meta:
        verbose_name = u'域名信息管理'
        verbose_name_plural = u'域名信息管理'

    def __unicode__(self):
        return self.domain_name

class Asset(models.Model):
    asset_type = models.IntegerField(choices=ASSET_TYPE,blank=True, null=True, verbose_name=u"主机类型")
    sn = models.CharField(u'资产SN号', max_length=128, unique=True)
    host_name = models.CharField(u'主机名',max_length=64,blank=True,null=True)
    p_ip = models.GenericIPAddressField(u'公网IP',unique=True)
    mac = models.CharField(u'MAC地址',max_length=128,blank=True,null=True)
    idc = models.ForeignKey(idc_list, blank=True, null=True, on_delete=models.SET_NULL)
    project = models.ForeignKey(Project, default=None, blank=True, null=True, on_delete=models.SET_NULL)
    other_ip = models.CharField(u'所有地址',max_length=255,blank=True,null=True)
    system_version = models.CharField(u'系统版本',max_length=32)
    cpu_type = models.CharField(u'CPU型号',max_length=128)
    cpu_core = models.IntegerField(u'CPU个数')
    cpu_total = models.IntegerField(u'CPU核数',)
    memory = models.CharField(u'内存',max_length=128, blank=True, null=True)
    disk_info = models.CharField(u'磁盘信息',max_length=512,blank=True,null=True)
    disk_mount = models.CharField(u'挂载分区',max_length=512,blank=True,null=True)
    server_type = models.CharField(u'服务器型号',max_length=64,blank=True,null=True)
    os_kernel = models.CharField(u'系统内核版本',max_length=255,blank=True,null=True)
    system_arch = models.CharField(u'系统平台',max_length=32,blank=True,null=True)
    status = models.IntegerField(choices=ASSET_STATUS, blank=True, null=True, default=1,verbose_name="设备状态")
    admin = models.ForeignKey(UserProfile, verbose_name=u'资产管理员', null=True, blank=True)
    create_date = models.DateTimeField(blank=True, auto_now_add=True)
    update_date = models.DateTimeField(blank=True, auto_now=True)

    class Meta:
        verbose_name = '资产总表'
        verbose_name_plural = "资产总表"

    def __unicode__(self):
        return self.sn

class KeyManager(models.Model):
    project = models.ForeignKey(Project,blank=True, null=True, on_delete=models.SET_NULL,verbose_name="绑定项目")
    name = models.CharField(u'密钥名称',max_length=64,blank=True,null=True)
    username = models.CharField(u'系统用户',max_length=32,blank=True,null=True)
    password = models.CharField(u'SSH密码', max_length=64,blank=True,null=True)
    private_key = models.TextField(u'私钥内容')
    public_key = models.TextField(u'公钥内容')
    create_date = models.DateTimeField(blank=True, auto_now_add=True)
    operator = models.ForeignKey(UserProfile,max_length=84,verbose_name="管理员")

    class Meta:
        verbose_name = '超级用户管理'
        verbose_name_plural = "超级用户管理"

    def __unicode__(self):
        return self.name

class CommonUser(models.Model):
    project = models.ForeignKey(Project, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="所属项目")
    username = models.CharField(u'普通用户',max_length=32,blank=True,null=True)
    password = models.CharField(u'密码',max_length=32,blank=True,null=True)
    private_key = models.TextField(u'私钥内容',blank=True,null=True)
    public_key = models.TextField(u'公钥内容',blank=True,null=True)
    create_date = models.DateTimeField(blank=True, auto_now_add=True)

hosts/views/AuditLog.py
#!/usr/bin/env python
#-*- coding: utf-8 -*-
from django.shortcuts import render,HttpResponseRedirect,render_to_response,HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response,RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from manager.views.permission import *
from hosts.models import  *
from manager.myauth import *
from manager.common import *
from django.db.models import Q
import datetime


def clear_30days_ago():
    now_time = datetime.datetime.now()
    yes_time = now_time + datetime.timedelta(days=-30)
    yes_time_nyr = yes_time.strftime('%Y-%m-%d')
    try:
        del_info = SshAuditLog.objects.filter(log_time__lte="%s 00:00:00" % yes_time_nyr)
        del_info.delete()
        return True
    except:
        return False


@login_required
@PermissionVerify()
def log_list(request):
    header_title, nav, tip = "日志审计", "审计", "操作审计"

    ip = request.GET.get("ip")

    if request.method == 'GET':
        project = request.GET.get("project")

    else:
        project = request.POST.get("project")
        search_name = request.POST.get("search_name")

        try:
            if search_name:
                log_info = SshAuditLog.objects.filter(Q(p_ip__contains=search_name) |
                                                      Q(username__contains=search_name) |
                                                      Q(project__name__contains=search_name) |
                                                      Q(project__mini_name__contains=search_name) |
                                                      Q(login_ip__contains=search_name) |
                                                      Q(cmd_log__contains=search_name))

                return render_to_response('hosts/log_list.html', locals(), context_instance=RequestContext(request))
        except Exception, e:
            error = "%s"%e

    log_info = SshAuditLog.objects.filter(project__mini_name=project).order_by('-log_time')

    iUser = UserProfile.objects.get(email="%s" % request.user)

    if iUser.is_admin:
        pro_info = Project.objects.all()
    else:
        pro_info = iUser.project.all()

    clear_30days_ago

    pro_list  = []
    for pro in pro_info:
        pro_dict={}
        pro_dict['name'] = pro.name
        pro_dict['mini_name'] = pro.mini_name
        pro_dict['cmd_count'] = SshAuditLog.objects.filter(project__mini_name=project).count()
        pro_list.append(pro_dict)

    if ip is not None:
        log_info = SshAuditLog.objects.filter(p_ip=ip).order_by('-log_time')


    return render_to_response('hosts/log_list.html', locals(), context_instance=RequestContext(request))



hosts/views/DomainInfo.py
#!/usr/bin/env python
#-*- coding: utf-8 -*-

from manager.common import *
from manager.views.permission import *

@login_required
@PermissionVerify()
def domain_list(request):
    header_title, nav, tip = "域名信息管理", "域名列表", "域名信息管理"

    af = DomainInfoForm()

    if request.method == 'POST':
        action = request.POST.get("action")
    else:
        action = request.GET.get("action")

    if action == "delete":
        key_id = request.GET.get("id")
        del_key = DomainInfo.objects.filter(id=key_id)
        del_key.delete()

    elif action == "add":
        if request.method == 'POST':
            af_post = DomainInfoForm(request.POST)
            domain_name = request.POST.get('domain_name', '')
            try:
                if DomainInfo.objects.filter(domain_name=domain_name):
                    error = u'域名 %s 已存在!' % domain_name
            except Exception:
                pass

            else:
                if af_post.is_valid():
                    af_save = af_post.save(commit=False)
                    af_save.save()
                    af_post.save_m2m()
                else:
                    msg = "域名 %s 添加失败" % domain_name

    iUser = UserProfile.objects.get(email="%s" % request.user)
    if iUser.is_admin:
        domain_info = DomainInfo.objects.all()
    else:
        project_info = iUser.project.all()
        pro_list = []
        for i in project_info:
            mini_name = i.mini_name
            pro_list.append(mini_name)

        domain_info = DomainInfo.objects.filter(project__mini_name__in=pro_list)

    return render_to_response('hosts/domain_list.html', locals(), context_instance=RequestContext(request))





templates/hosts/area_list.html
{% extends 'base.html' %}
{% load humanize %}
{% block page-content %}
{% include 'nav_cat_bar.html' %}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>{{tip}} </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">Config option 1</a>
                            </li>
                            <li><a href="#">Config option 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="row">
                      <div class="col-sm-4 m-b-xs">
                          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#area_add"><i class="icon-cogs"></i>增加</button>
                      </div>
                  </div>
                {% if error %}
                    <div class="alert alert-warning text-center">{{ error }}</div>
                {% endif %}
                {% if add_info %}
                    <div class="alert alert-success text-center">{{ add_info }}</div>
                {% endif %}
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th class="text-center">地区</th>
                                <th class="text-center">简称</th>
                                <th class="text-center">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for p in area_info %}
                                  <tr class="text-center">
                                    <td>{{p.area_name}}</td>
                                    <td>{{p.mini_name}}</td>
                                    <td>
                                    <a href="/hosts/area_edit/?id={{p.id}}"><span class="glyphicon glyphicon-pencil"></span></a>
                                    <a href="/hosts/area_list/?name={{p.area_name}}&action=delete"><span style="color:red" class="glyphicon glyphicon-trash" onclick="return confirm('确认删除吗？')"></span></a>
                                    </td>

                                  </tr>
                                 {% endfor %}
                            </tbody>
                        </table>
                       <div class="col-sm-6">
                            <div class="dataTables_info" id="editable_info" role="status" aria-live="polite">
                                  Showing {{ contacts.start_index }} to {{ contacts.end_index }} of {{ p.count }} entries
                            </div>
                        </div>
                           {% include 'paginator.html' %}
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="area_add" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel" align="center">添加地区</h4>
      </div>
      <div class="modal-body">
<form id="area_form" method="post" class="form-horizontal" action="">
	<div class="form-group">
		<label for="group_name" class="col-sm-2 control-label">名称<span class="red-fonts">*</span></label>
		<div class="col-sm-8">
			<input id="area_name" name="area_name" placeholder="日本" type="text" class="form-control" >
		</div>
	</div>
	<div class="hr-line-dashed"></div>
	<div class="form-group">
		<label for="comment" class="col-sm-2 control-label">简称</label>
		<div class="col-sm-8">
			<input id="area_mini" name="area_mini" placeholder="jp" type="text" class="form-control">
		</div>
	</div>
</form>
</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="submit" class="btn btn-primary" form="area_form" formmethod="post" formaction="{% url 'area_list' %}" name="action" value="add">确定</button>
      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/hosts/cost_list.html
{% extends 'base.html' %}
{% load humanize %}
{% block page-content %}
{% include 'nav_cat_bar.html' %}
{% load bootstrap %}
<link href="/static/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="/static/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="/static/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">

<div class="wrapper wrapper-content">
    <div class="row">
        <div id="idc_cost" class="col-lg-6" style="height:400px"></div>
        <div id="pro_cost" class="col-lg-6" style="height:400px"></div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>费用信息</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">未启用 1</a>
                            </li>
                            <li><a href="#">未启用 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    <div class="row">
                      <div class="col-sm-4 m-b-xs">
                          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#idc_add"><i class="icon-cogs"></i>增加</button>
                      </div>
                    </div>
                    {% if error %}
                        <div class="alert alert-warning text-center">{{ error }}</div>
                    {% endif %}
                    {% if msg %}
                        <div class="alert alert-success text-center">{{ msg }}</div>
                    {% endif %}
                    <table class="table table-striped table-bordered table-hover dataTables-example">
                          <thead>
                            <th class="text-center">项目</th>
                            <th class="text-center">云服务类型</th>
                            <th class="text-center">IDC</th>
                            <th class="text-center">CPU</th>
                            <th class="text-center">内存</th>
                            <th class="text-center">磁盘</th>
                            <th class="text-center">带宽</th>
                            <th class="text-center">按量计费</th>
                            <th class="text-center">开始时间</th>
                            <th class="text-center">状态</th>
                            <th class="text-center">单价</th>
                            <th class="text-center">数量</th>
                            <th class="text-center">操作</th>
                          </thead>
                          <tbody>
                            {% for num in cost_info %}
                              <tr class="text-center">
                                <td>{{num.project.name}}</td>
                                <td>{{num.get_cost_type_display}}</td>
                                <td>{{num.idc.idc_name}}</td>
                                <td>{{num.cpu}}核</td>
                                <td>{{num.mem}}GB</td>
                                <td>{{num.disk}}GB</td>
                                <td>{{num.bandwidth}}MB</td>
                                {% if num.network_bill == 1 %}
                                    <td>是</td>
                                {% else %}
                                    <td>否</td>
                                {% endif %}
                                <td>{{num.start_date|date:"Y-m-d H:i:s"}}</td>
                                <td>{{num.get_status_display}}</td>
                                <td>{{num.price}}</td>
                                <td>{{num.total}}</td>
                                <td>
                                    <a href="{% url 'cost_list' %}?id={{num.id}}&action=plus"><span class="glyphicon glyphicon-plus"></span></a>
                                    &nbsp;
                                    <a href="{% url 'cost_list' %}?id={{num.id}}&action=minus"><span style="color:red" class="glyphicon glyphicon-minus"></span></a>
                                    &nbsp;
                                    <a href="{% url 'cost_edit' %}?id={{num.id}}"><span class="glyphicon glyphicon-pencil"></span></a>
                                    &nbsp;&nbsp;
                                    <a href="{% url 'cost_list' %}?id={{num.id}}&action=delete"><span style="color:red" class="glyphicon glyphicon-trash" onclick="return confirm('确认删除吗？')"></span></a>
                                </td>
                              </tr>
                            {% endfor %}
                          </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="idc_add" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel" align="center">添加费用信息</h4>
      </div>
        <div class="modal-body">
            <form id="CostMangerForm" method="post" class="form-horizontal">
                {{ af.project|bootstrap_horizontal }}
                {{ af.cost_type|bootstrap_horizontal }}
                {{ af.idc|bootstrap_horizontal }}
                {{ af.cpu|bootstrap_horizontal }}
                {{ af.mem|bootstrap_horizontal }}
                {{ af.disk|bootstrap_horizontal }}
                {{ af.bandwidth|bootstrap_horizontal }}
                {{ af.network_bill|bootstrap_horizontal }}
                {{ af.price|bootstrap_horizontal }}
                {{ af.status|bootstrap_horizontal }}
                {{ af.total|bootstrap_horizontal }}
            </form>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="submit" class="btn btn-primary" form="CostMangerForm" formmethod="post" formaction="{% url 'cost_list' %}" name="action" value="add">确定</button>
      </div>
    </div>
  </div>
</div>

<script src="/static/js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="/static/js/plugins/dataTables/dataTables.bootstrap.js"></script>
<script src="/static/js/plugins/dataTables/dataTables.responsive.js"></script>
<script src="/static/js/plugins/dataTables/dataTables.tableTools.min.js"></script>

<script type="text/javascript">
$(document).ready(function() {
            $('.dataTables-example').dataTable({
                responsive: true,
                "dom": 'T<"clear">lfrtip',
                "iDisplayLength":10,
                "tableTools": {
                    "aButtons":["copy","xls",'print'],
                    "sSwfPath": "/static/js/plugins/dataTables/swf/copy_csv_xls_pdf.swf"
                }
            });
        });

</script>

<script>
$(function() {
    Highcharts.setOptions({
        timezoneOffset: -8
    });

    $.getJSON("{% url 'cost_idc_api' %}", function(json) {
        $('#idc_cost').highcharts({
            chart: {
                type: 'line'
            },
            title: {
                text: '云服务器新增消费曲线'
            },
            subtitle: {
                text: json.subtitle
            },
            xAxis: {
                categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
            },
            yAxis: {
                title: {
                    text: '月度新增消费'
                }
            },
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                    },
                    enableMouseTracking: false
                }
            },
            series: json.data,
        });
    });
});
</script>

<script>
$(function() {
    Highcharts.setOptions({
        timezoneOffset: -8
    });

    $.getJSON("{% url 'cost_pro_api' %}", function(json) {
        $('#pro_cost').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: '项目月费用柱状图'
        },
        subtitle: {
            text: json.subtitle
        },
        xAxis: {
           // categories: [{% for p in spro_info %} '{{ p }}', {% endfor %}],
            categories: json.project,
            title: {
                text: null
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: '',
                align: 'high'
            },
            labels: {
                overflow: 'justify'
            }
        },
        tooltip: {
            valueSuffix: 'RMB'
        },
        plotOptions: {
            bar: {
                dataLabels: {
                    enabled: true
                }
            }
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'top',
            x: -40,
            y: 100,
            floating: true,
            borderWidth: 1,
            backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
            shadow: true
        },
        credits: {
            enabled: false
        },
        series: json.data
        });
    });
});
</script>

{%endblock%}